// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ciozbquqgfypwvgezxof.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNpb3picXVxZ2Z5cHd2Z2V6eG9mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMTA3ODIsImV4cCI6MjA2NDY4Njc4Mn0.2F_uAiP8axzrV2epNPyx2IP9XaP3xfE7aWtHJinrCAU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);